version: '3.8'
services:
  mongo:
    image: mongo:5.0
    ports:
      - 27017:27017
    #volumes:
    #- ./data/db:/data/db
    networks:
      - backend
    #environment:
    #- MONGO_INITDB_ROOT_USERNAME=admin
    env_file: .env

  flaskrest:
    build: ./
    ports:
    - target: 5000
      published: 5060
      protocol: tcp
      mode: host
    volumes:
      - ./src:/src
    networks:
      - backend
    env_file: .env
    depends_on: 
    - mongo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5050"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  backend: